name: 'useprivaction'
description: 'Use priv action'
inputs:
  action:
    required: true
    type: string
  ref:
    required: true
    type: string
  token:
    required: true
    type: string
  subpath:
    required: true
    type: string
  access_key:
    required: true
    type: string
  secret_key:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Get composite run steps repository
      uses: actions/checkout@v2
      with:
        repository: ${{ inputs.action }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        path: ./.github/useprivation

    - run: |
        mkdir -p ./.github/workflows/priv
        cp ./.github/useprivation/${{inputs.subpath}} ./.github/workflows/priv/action.yml
      shell: bash

    - runs: ./.github/workflows/priv
      with:
        project_name: ${{ inputs.project_name }}
